services:
  postgres:
    image: postgres:15-alpine
    container_name: kentucky-baked-pizza-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: kentucky_baked_pizza
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - kentucky-baked-pizza-network
